import { Inter } from "next/font/google";
import "./globals.css";

import { AppProvider } from "./components/AppContext";
import Header from "./components/layout/Header";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "wellness-Wonders",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <AppProvider>
          <Header />
          {children}
        </AppProvider>

      </body>
    </html>
  );
}
